#!/bash

echo "🚀 GitHub推送 - 终极解决方案"
echo "=============================="
echo ""

cd ~/bilibili-digest

echo "📊 准备推送的内容："
echo "   ✅ 5个commits"
echo "   ✅ 27个文件"
echo "   ✅ 完整的B站AI摘要系统"
echo ""

echo "第1步：创建GitHub仓库"
echo "====================="
echo ""
echo "正在打开GitHub创建页面..."
open "https://github.com/new?name=bilibili-ai-digest&description=Bilibili+AI+Digest+System&public=true"

echo "✅ 已在浏览器中打开创建页面"
echo ""
echo "请确认以下信息："
echo "   仓库名：bilibili-ai-digest"
echo "   描述：Bilibili AI Digest System"
echo "   可见性：Public"
echo "   ⚠️ 不要勾选任何初始化选项"
echo ""
echo "点击绿色按钮：Create repository"
echo ""

read -p "创建完成后按回车继续..."

echo ""
echo "第2步：推送代码到GitHub"
echo "======================="
echo ""
echo "🔧 配置远程仓库..."
git remote set-url origin git@github.com:yninmc7-mc/bilibili-ai-digest.git

echo "📊 推送信息："
echo "   目标: git@github.com:yninmc7-mc/bilibili-ai-digest.git"
echo "   分支: main"
echo "   Commits: $(git log --oneline | wc -l | tr -d ' ')"
echo "   文件: $(git ls-files | wc -l | tr -d ' ')"
echo ""

echo "🚀 开始推送..."
echo ""

# 执行推送
if git push -u origin main 2>&1; then
    echo ""
    echo "🎉 成功！代码已推送到GitHub！"
    echo ""
    echo "📍 仓库地址: https://github.com/yninmc7-mc/bilibili-ai-digest"
    echo ""
    echo "✅ 推送完成的内容:"
    git log --oneline -5
    echo ""
    echo "📊 文件统计:"
    echo "   总文件: $(git ls-files | wc -l | tr -d ' ')"
    echo "   总行数: $(git ls-files | xargs wc -l | tail -1 | awk '{print $1}')"
    echo ""
    echo "🌐 在浏览器中查看仓库..."
    open "https://github.com/yninmc7-mc/bilibili-ai-digest"
    echo ""
    echo "🎊 恭喜！你的B站AI摘要系统已在GitHub上线！"
    echo ""
    echo "📋 系统功能："
    echo "   ✅ 17个AI/科技UP主监控"
    echo "   ✅ 每日自动扫描新视频（7:30AM）"
    echo "   ✅ 双语摘要生成（中英文）"
    echo "   ✅ 飞书自动推送"
    echo "   ✅ 完整的自动化脚本和配置"
    echo ""
    echo "🚀 GitHub推送完成！"
    echo ""
    echo "📝 下一步："
    echo "1. 在GitHub上查看你的代码"
    echo "2. 测试系统功能：bash ~/bilibili-digest/scripts/scheduled-digest.sh"
    echo "3. 确认定时任务设置：crontab -l | grep bilibili"
else
    echo ""
    echo "❌ 推送失败"
    echo ""
    echo "故障排除："
    echo "1. 确认仓库是否真的创建成功"
    echo "   访问: https://github.com/yninmc7-mc/bilibili-ai-digest"
    echo ""
    echo "2. 测试SSH连接"
    echo "   运行: ssh -T git@github.com"
    echo ""
    echo "3. 检查仓库权限"
    echo "   确认你是仓库的所有者或协作者"
    echo ""
    echo "🔄 重试命令: cd ~/bilibili-digest && git push -u origin main"
    echo ""
    echo "🔄 重新运行: bash ~/bilibili-digest/ultimate-push.sh"
    exit 1
fi
